// Auto-generated by: https://github.com/pmndrs/gltfjsx

import { Float, useGLTF } from '@react-three/drei';


const CandyCane = (props) => {
  const { nodes, materials } = useGLTF('models/candy_cane.glb');

  return (
    <Float floatIntensity={1}>
        <group position={[8, 8, 0]} scale={0.3} {...props} dispose={null}>
            <mesh
                geometry={nodes['ZBrush_defualt_group_candy_cane-red_0'].geometry}
                material={materials['candy_cane-red']}
                castShadow
                receiveShadow
                position={[0, 0.079, 0.181]}
                rotation={[0, 0, 0]}
                scale={[0.1, 0.1, 0.1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['ZBrush_defualt_group_candy_cane-red_0_1'].geometry}
                material={materials['candy_cane-red']}
                position={[0, 0.079, 0.181]}
                rotation={[0, 0, 0]}
                scale={[0.1, 0.1, 0.1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZBrush_defualt_group_WHITE_CANDY_CANE_1.geometry}
                material={materials.WHITE_CANDY_CANE}
                position={[0, 0.079, 0.181]}
                rotation={[0, 0, 0]}
                scale={[0.1, 0.1, 0.1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ZBrush_defualt_group_WHITE_CANDY_CANE_1_1.geometry}
                material={materials.WHITE_CANDY_CANE}
                position={[0, 0.079, 0.181]}
                rotation={[0, 0, 0]}
                scale={[0.1, 0.1, 0.1]}
            />
        </group>
    </Float>
  );
};

useGLTF.preload('models/candy_cane.glb');

export default CandyCane;
